cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --time={resources.time}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
    --error=logs/{rule}/{rule}-{wildcards}-%j.err
default-resources:
  - slurm_account=mteleman
  - tmpdir='/scratch/mteleman/snakemake_tmp/'  # location of the folder where snakemake should save the tmp files
restart-times: 3 # this will allow to re-run a job 3 time maximum if it fails (usefull if we specify in the rule to increase memory in each attempt)
latency-wait: 120
jobs: 500 # to say that we wwant that a maximum of 100 jobs are launched on the cluster
keep-going: True  #Go on with independent jobs if a job fails
rerun-incomplete: True  #Re-run all jobs the output of which is recognized as incomplete
printshellcmds: True  #Print out the shell commands that will be executed
use-singularity: True  #If defined in the rule, run job within a singularity container. If this flag is not set, the singularity directive is ignored
